version: '3.7'
services:
  jointscamp_db:
    container_name: jointscamp_db
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/jointscamp
      - POSTGRES_PASSWORD=jointscamp
    volumes:
      - postgres_jointscamp_volume:/var/lib/postgresql/data/jointscamp
volumes:
  postgres_jointscamp_volume: